"""Add agent state to conversations

Revision ID: 07b43128b130
Revises: c126d8aba71a
Create Date: 2025-07-14 14:30:46.608799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07b43128b130'
down_revision = 'c126d8aba71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.Enum('COMPLETE', 'PROCESSING', 'THINKING', 'TRANSCRIBING', 'STREAMING', 'FAILED', name='messagestatus'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('COMPLETE', 'PROCESSING', 'THINKING', 'TRANSCRIBING', 'STREAMING', 'FAILED', name='messagestatus'),
               type_=mysql.VARCHAR(length=25),
               nullable=True)

    # ### end Alembic commands ###
