"""Add agent state to conversations

Revision ID: 0cb764a0e7fa
Revises: 07b43128b130
Create Date: 2025-07-14 14:33:35.382745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb764a0e7fa'
down_revision = '07b43128b130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agent_state', sa.JSON(), nullable=True, comment='Stores state for multi-step agent conversations'))
        batch_op.create_foreign_key(None, 'agents', ['agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agent_state')
        batch_op.drop_column('agent_id')

    # ### end Alembic commands ###
