"""Add job tracking fields to Message model

Revision ID: 3afac83cd17c
Revises: 7b92e338e293
Create Date: 2025-07-22 11:06:46.578036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afac83cd17c'
down_revision = '7b92e338e293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_message_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('job_status', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('job_metadata', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'messages', ['parent_message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_metadata')
        batch_op.drop_column('job_status')
        batch_op.drop_column('parent_message_id')

    # ### end Alembic commands ###
