"""Remove legacy AIModel tables

Revision ID: 6875e92100b0
Revises: 40f0d70d3503
Create Date: 2025-07-10 15:46:27.750338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6875e92100b0'
down_revision = '40f0d70d3503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_assigned_models')
    op.drop_table('ai_models')
    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assigned_models',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_id', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], name=op.f('user_assigned_models_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_assigned_models_ibfk_1')),
    sa.PrimaryKeyConstraint('user_id', 'model_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ai_models',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('api_key_encrypted', mysql.TEXT(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
