"""Add video_context_url to Conversation model

Revision ID: 6cf469321e39
Revises: 5660686d1d46
Create Date: 2025-07-29 01:09:32.980581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf469321e39'
down_revision = '5660686d1d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_context_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('video_context_url')

    # ### end Alembic commands ###
