"""Add tts_voice to User model

Revision ID: 7b92e338e293
Revises: 8bc739791c76
Create Date: 2025-07-20 12:12:46.299742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b92e338e293'
down_revision = '8bc739791c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tts_voice', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tts_voice')

    # ### end Alembic commands ###
