"""Add image_prompt to Message model

Revision ID: 8bc739791c76
Revises: e1ddc8f7b1d7
Create Date: 2025-07-19 11:34:44.170368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc739791c76'
down_revision = 'e1ddc8f7b1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('image_prompt')

    # ### end Alembic commands ###
