"""Add video editing fields to Message model

Revision ID: a7c211eff6fe
Revises: 3afac83cd17c
Create Date: 2025-07-23 12:18:55.674911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c211eff6fe'
down_revision = '3afac83cd17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_message_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('edit_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'messages', ['edited_message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('version')
        batch_op.drop_column('edit_instructions')
        batch_op.drop_column('edited_message_id')

    # ### end Alembic commands ###
