"""Manually widen status column in messages table

Revision ID: c126d8aba71a
Revises: 6875e92100b0
Create Date: 2025-07-14 13:05:24.022009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c126d8aba71a'
down_revision = '6875e92100b0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- ADD THIS BLOCK ---
    op.alter_column(
        'messages',
        'status',
        type_=sa.String(length=25), # Widen the column to 25 characters
        existing_type=sa.Enum('COMPLETE', 'THINKING', 'TRANSCRIBING', 'STREAMING', 'ERROR', 'FAILED', 'UPLOADING', 'WAITING'),
        nullable=True
    )
    # --- END OF BLOCK ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- ADD THIS BLOCK ---
    op.alter_column(
        'messages',
        'status',
        type_=sa.Enum('COMPLETE', 'THINKING', 'TRANSCRIBING', 'STREAMING', 'ERROR', 'FAILED', 'UPLOADING', 'WAITING'),
        existing_type=sa.String(length=25),
        nullable=True
    )
    # --- END OF BLOCK ---
    
    # ### end Alembic commands ###
