"""Create unified cost and logging tables

Revision ID: e1ddc8f7b1d7
Revises: 0cb764a0e7fa
Create Date: 2025-07-16 17:16:08.087016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ddc8f7b1d7'
down_revision = '0cb764a0e7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_costs_service_key'), ['service_key'], unique=True)

    op.create_table('transaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('service_cost_id', sa.Integer(), nullable=False),
    sa.Column('units_consumed', sa.Float(), nullable=False),
    sa.Column('cost_deducted', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_cost_id'], ['service_costs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_logs_service_cost_id'), ['service_cost_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_logs_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_logs_team_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_logs_service_cost_id'))

    op.drop_table('transaction_logs')
    with op.batch_alter_table('service_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_costs_service_key'))

    op.drop_table('service_costs')
    # ### end Alembic commands ###
